name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        module:
          - serial
          - usbip
    env:
      IMAGE_NAME: ghcr.io/silvenga-docker/usb-modules/${{ matrix.module }}
    steps:
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v4
        id: build
        with:
          file: Dockerfile
          context: "{{defaultContext}}:src/${{ matrix.module }}"
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: ${{ github.actor != 'dependabot[bot]' && format('type=registry,ref={0}:cache', env.IMAGE_NAME) || ''}}
          cache-to: ${{ github.actor != 'dependabot[bot]' && format('type=registry,ref={0}:cache,mode=max', env.IMAGE_NAME) || ''}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
